### ISSUE TITLE
Stuck when stopping server

### ISSUE THREAD

**Issue by BirkhoffLee** [sladkoff/minecraft-prometheus-exporter#10]
Part of the logs:

```
[11:04:01 INFO]: [ClearChat] Disabling ClearChat v3.0.1
[11:04:01 INFO]: [KeepItems] Disabling KeepItems v1.3.2
[11:04:01 INFO]: [PrometheusExporter] Disabling PrometheusExporter v1.1.0
[11:04:01 WARN]: 2017-06-17 11:04:01.354:INFO:oejs.AbstractConnector:Server thread: Stopped ServerConnector@1429aebf{HTTP/1.1,[http/1.1]}{0.0.0.0:9225}

(stuck here for 15 sec)

[11:04:16 WARN]: [PrometheusExporter] Failed to read server statistics
[11:04:16 WARN]: java.lang.InterruptedException
[11:04:16 WARN]: 	at java.lang.Object.wait(Native Method)
[11:04:16 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.get(CraftFuture.java:54)
[11:04:16 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.get(CraftFuture.java:42)
[11:04:16 WARN]: 	at de.sldk.mc.MetricsController.handle(MetricsController.java:68)
[11:04:16 WARN]: 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[11:04:16 WARN]: 	at org.eclipse.jetty.server.Server.handle(Server.java:564)
[11:04:16 WARN]: 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
[11:04:16 WARN]: 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[11:04:16 WARN]: 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
[11:04:16 WARN]: 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
[11:04:16 WARN]: 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
[11:04:16 WARN]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
[11:04:16 WARN]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
[11:04:16 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:04:16 INFO]: Saving players
[11:04:16 INFO]: Saving worlds
[11:04:16 INFO]: Saving chunks for level 'sb1_spawn'/Overworld
[11:04:16 INFO]: Saving chunks for level 'Skyblock1'/Overworld
[11:04:16 INFO]: Saving chunks for level 'Skyblock1_nether'/Nether
```

**Comment by sladkoff** [comment]
This warning should only occur when Prometheus scrapes your server just when the server is shutting down. I might remove the error log.

I doubt that it's the plugin causing the 15sec delay. Are you able to reproduce this @BirkhoffLee each time when shutting down the server?

**Comment by BirkhoffLee** [comment]
Sometimes it won't happen. So I think maybe you're right
