### ISSUE TITLE
[Bug Report] Exception fetching statistic KILL_ENTITY from player

### ISSUE THREAD

**Issue by rudxde** [sladkoff/minecraft-prometheus-exporter#143]
Hi, im getting regularly the following log to my console:

```
[12:48:13 WARN]: [PrometheusExporter] Exception fetching statistic KILL_ENTITY from player
java.lang.IllegalArgumentException: The supplied EntityType does not have a corresponding statistic
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.craftbukkit.v1_18_R1.CraftStatistic.getStatistic(CraftStatistic.java:280) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.getStatistic(CraftPlayer.java:1237) ~[paper-1.18.1.jar:git-Paper-186]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.getTypedStatistic(PlayerStatisticLoaderFromBukkit.java:82) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.lambda$getPlayerStatistics$1(PlayerStatisticLoaderFromBukkit.java:52) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657) ~[?:?]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.lambda$getPlayerStatistics$2(PlayerStatisticLoaderFromBukkit.java:53) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.getPlayerStatistics(PlayerStatisticLoaderFromBukkit.java:48) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at de.sldk.mc.metrics.PlayerStatistics.collectSuccessful(PlayerStatistics.java:59) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at de.sldk.mc.metrics.PlayerStatistics.collect(PlayerStatistics.java:48) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at de.sldk.mc.metrics.PlayerMetric.doCollect(PlayerMetric.java:21) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at de.sldk.mc.metrics.Metric.collect(Metric.java:34) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at de.sldk.mc.MetricRegistry.collectMetrics(MetricRegistry.java:27) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at de.sldk.mc.MetricsController.lambda$handle$0(MetricsController.java:39) ~[minecraft-prometheus-exporter-2.4.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-186]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Server:
```
Papermc 1.18.1 build 186
with java openjdk:17

```

Config:
```
host: 0.0.0.0
port: 9090
enable_metrics:
  entities_total: true
  villagers_total: true
  loaded_chunks_total: true
  jvm_memory: true
  players_online_total: true
  players_total: true
  tps: true
  jvm_threads: true
  jvm_gc: true
  tick_duration_median: true
  tick_duration_average: true
  tick_duration_min: false
  tick_duration_max: true
  player_online: true
  player_statistic: true
```

**Comment by NapoSky** [comment]
Bump, same happens with Spigot 1.18.2 on openjdk:17 too.

**Comment by NapoSky** [comment]
@sladkoff any ideas ?

**Comment by lmichaelis** [comment]
This is due to `player.getStatistic(statistic, (EntityType) statType);` throwing when `statType` is `EntityType.UNKNOWN`. You could just return `0` for `EntityType.UNKNOWN` or exclude it from the statistics entirely by removing that entry from `ENTITY_TYPES` when initializing it.
