### ISSUE TITLE
On shutdown, I get a big error

### ISSUE THREAD

**Issue by kelso6969** [sladkoff/minecraft-prometheus-exporter#16]
[16:39:39 WARN]: [PrometheusExporter] Failed to read server statistic: null
[16:39:39 WARN]: java.lang.InterruptedException
[16:39:39 WARN]:        at java.lang.Object.wait(Native Method)
[16:39:39 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.get(CraftFuture.java:50)
[16:39:39 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.get(CraftFuture.java:38)
[16:39:39 WARN]:        at de.sldk.mc.MetricsController.handle(MetricsController.java:81)
[16:39:39 WARN]:        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[16:39:39 WARN]:        at org.eclipse.jetty.server.Server.handle(Server.java:564)
[16:39:39 WARN]:        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
[16:39:39 WARN]:        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[16:39:39 WARN]:        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
[16:39:39 WARN]:        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
[16:39:39 WARN]:        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
[16:39:39 WARN]:        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
[16:39:39 WARN]:        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
[16:39:39 WARN]:        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
[16:39:39 WARN]:        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
[16:39:39 WARN]:        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
[16:39:39 WARN]:        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
[16:39:39 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by sladkoff** [comment]
Thanks for the report. The exception logging was very verbose. That should be better in the latest version.
