### ISSUE TITLE
[Azul] Exception on startup: Monitoring of Synchronizer Usage is not supported.

### ISSUE THREAD

**Issue by MG8853** [sladkoff/minecraft-prometheus-exporter#197]
```
[17:32:23 INFO]: [PrometheusExporter] Enabling PrometheusExporter v2.5.0
[17:32:23 ERROR]: Error occurred while enabling PrometheusExporter v2.5.0 (Is it up to date?)
java.lang.UnsupportedOperationException: Monitoring of Synchronizer Usage is not supported.
        at sun.management.ThreadImpl.findDeadlockedThreads(ThreadImpl.java:431) ~[?:?]
        at io.prometheus.client.hotspot.ThreadExports.addThreadMetrics(ThreadExports.java:95) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at io.prometheus.client.hotspot.ThreadExports.collect(ThreadExports.java:156) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at io.prometheus.client.hotspot.ThreadExports.collect(ThreadExports.java:150) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at de.sldk.mc.metrics.HotspotPrefixer.prefixFromCollector(HotspotPrefixer.java:12) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at de.sldk.mc.metrics.ThreadsWrapper$ThreadExportsCollector.collect(ThreadsWrapper.java:23) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:113) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at de.sldk.mc.metrics.Metric.enable(Metric.java:54) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at de.sldk.mc.config.PrometheusExporterConfig.lambda$enableConfiguredMetrics$1(PrometheusExporterConfig.java:67) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at java.util.Arrays$ArrayList.forEach(Arrays.java:4220) ~[?:?]
        at de.sldk.mc.config.PrometheusExporterConfig.enableConfiguredMetrics(PrometheusExporterConfig.java:62) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at de.sldk.mc.PrometheusExporter.onEnable(PrometheusExporter.java:18) ~[minecraft-prometheus-exporter-2.5.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-194]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-194]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-194]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-194]
        at java.lang.Thread.run(Thread.java:891) ~[?:?]
[17:32:23 INFO]: [PrometheusExporter] Disabling PrometheusExporter v2.5.0
[17:32:23 WARN]: [PrometheusExporter] Failed to stop metrics server gracefully: Cannot invoke "de.sldk.mc.MetricsServer.stop()" because "this.server" is null
```
```
java version "17.0.8.1" 2023-09-06 LTS
Java Runtime Environment Zing23.08.0.0+3 (build 17.0.8.1+1-LTS)
Zing 64-Bit Tiered VM Zing23.08.0.0+3 (build 17.0.8.1-zing_23.08.0.0-b3-product-linux-X86_64, mixed mode)
```
```
minecraft server version 1.20.1
This server is running Paper version git-Paper-194 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 1b1c230)
```
```
java -Xms14G -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+PerfDisableSharedMem -XX:-ZUncommit -XX:+ParallelRefProcEnabled -Dterminal.jline=false -Dterminal.ansi=true -jar paper.jar
```
```
Ubuntu 20.04
```

**Comment by sladkoff** [comment]
Probably caused by https://github.com/prometheus/client_java/issues/866

**Comment by sladkoff** [comment]
@MG8853 This is a bug that I can not fix at the moment because it's caused by the linked dependency. It only affects certain JVM configurations (Azul). 

The workaround is to disable the `jvm_threads` metric on Azul or to use a different JVM implementation (e.g. OpenJDK).

I'll keep this ticket around until there's a fix in the upstream dependency.

**Comment by sladkoff** [comment]
I added a workaround so that the plugin should not completely crash when this happens. Still, the JVM metrics will not be available on Azul environments.
