### ISSUE TITLE
[Bug Report] Entities metric throws exceptions for server versions < 1.14

### ISSUE THREAD

**Issue by Mikgreg** [sladkoff/minecraft-prometheus-exporter#38]
Hello,

I have installed the exporter jar onto some of my servers and I'm getting the below stack error whenever the dashboard refreshes.

```
[12:11:29 WARN]: [PrometheusExporter] Task #33056 for PrometheusExporter v2.1.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.EntityType.getKey()Lorg/bukkit/NamespacedKey;
        at de.sldk.mc.metrics.Entities.getEntityName(Entities.java:60) ~[?:?]
        at de.sldk.mc.metrics.Entities.lambda$collect$0(Entities.java:51) ~[?:?]
        at java.util.HashMap$KeySet.forEach(HashMap.java:933) ~[?:1.8.0_191]
        at de.sldk.mc.metrics.Entities.collect(Entities.java:48) ~[?:?]
        at de.sldk.mc.metrics.WorldMetric.doCollect(WorldMetric.java:17) ~[?:?]
        at de.sldk.mc.metrics.Metric.collect(Metric.java:27) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_191]
        at de.sldk.mc.MetricRegistry.collectMetrics(MetricRegistry.java:27) ~[?:?]
        at de.sldk.mc.MetricsController.lambda$handle$0(MetricsController.java:46) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.run(CraftFuture.java:85) ~[spigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:852) ~[spigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[spigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[spigot.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

Along with this, the entities section of the dashboard is showing "No data".

https://i.imgur.com/g0RZ778.png

Everything else seems to be working fine though. I am using v2.1.0 of the Prometheus Exporter MC plugin.

Any help would be appreciated.

Thanks

**Comment by Mikgreg** [comment]
I should add this is happening across two different MC versions.

mSpigot version git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

and

Paper version git-Paper-33d42c8e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by sladkoff** [comment]
@Mikgreg Thanks for reporting this. Apparently version `2.1.0` of the exporter only supports server versions `1.14` and up so you are running into this problem.

I'll see what we can do about this. 

Internal note / commit with added methods for reference: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/67d908a9830c71267ee740f5bddd728ce9c64cc7#src/main/java/org/bukkit/entity/EntityType.java

**Comment by sladkoff** [comment]
@Mikgreg Can you please try this hotfix and let me know if that helps: https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v2.1.1/minecraft-prometheus-exporter-2.1.1.jar

**Comment by sladkoff** [comment]
@Mikgreg Please re-open if there are still any issues.
