### ISSUE TITLE
[Bug Report] Exception fetching statistic KILL_ENTITY from player

### ISSUE THREAD

**Issue by EpicnessTwo** [sladkoff/minecraft-prometheus-exporter#94]
Getting the following error on one of our servers. It's running Paper 1.17 Build 16

Error:

```
[23:58:56 WARN]: [PrometheusExporter] Exception fetching statistic KILL_ENTITY from player
java.lang.IllegalArgumentException: The supplied EntityType does not have a corresponding statistic
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftStatistic.getStatistic(CraftStatistic.java:280) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.getStatistic(CraftPlayer.java:1171) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.getTypedStatistic(PlayerStatisticLoaderFromBukkit.java:82) ~[?:?]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.lambda$getPlayerStatistics$1(PlayerStatisticLoaderFromBukkit.java:52) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657) ~[?:?]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.lambda$getPlayerStatistics$2(PlayerStatisticLoaderFromBukkit.java:53) ~[?:?]
        at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at de.sldk.mc.metrics.player.PlayerStatisticLoaderFromBukkit.getPlayerStatistics(PlayerStatisticLoaderFromBukkit.java:48) ~[?:?]
        at de.sldk.mc.metrics.PlayerStatistics.collectSuccessful(PlayerStatistics.java:59) ~[?:?]
        at de.sldk.mc.metrics.PlayerStatistics.collect(PlayerStatistics.java:48) ~[?:?]
        at de.sldk.mc.metrics.PlayerMetric.doCollect(PlayerMetric.java:21) ~[?:?]
        at de.sldk.mc.metrics.Metric.collect(Metric.java:34) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at de.sldk.mc.MetricRegistry.collectMetrics(MetricRegistry.java:27) ~[?:?]
        at de.sldk.mc.MetricsController.lambda$handle$0(MetricsController.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by c-goldschmidt** [comment]
same for `ENTITY_KILLED_BY`
